"""文档 Agent。"""

from __future__ import annotations

from project_09_dev_team.messages.models import Artifact, DevelopmentPlan, TestReport


class DocWriterAgent:
    """根据计划和测试报告生成项目文档。"""

    def write_docs(self, plan: DevelopmentPlan, test_report: TestReport) -> list[Artifact]:
        modules = "\n".join(f"- `{item['path']}`: {item['responsibility']}" for item in plan.modules)
        interfaces = "\n".join(f"- `{item}`" for item in plan.interfaces)
        return [
            Artifact(
                "README.md",
                f"""# {plan.project_name}

{plan.summary}

## Usage

Run the CLI with Python after installing no extra dependencies.

## Modules

{modules}

## Test Status

{test_report.summary}
""",
                "doc",
            ),
            Artifact(
                "API.md",
                f"""# API

## Interfaces

{interfaces}
""",
                "doc",
            ),
            Artifact(
                "ARCHITECTURE.md",
                f"""# Architecture

Requirement: {plan.requirement}

The project is generated by a four-agent teaching workflow:

1. Planner creates the development plan.
2. Developer emits structured code artifacts.
3. Tester runs static checks and whitelisted unittest.
4. DocWriter writes project documentation.
""",
                "doc",
            ),
        ]
